name: Build OpenCC on macOS ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 使工作流可以手动触发

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        platform: [arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install dependencies
      run: |
        brew install cmake boost

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: |
        cd build
        cmake .. -DCMAKE_OSX_ARCHITECTURES=arm64

    - name: Build OpenCC
      run: |
        cd build
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: opencc-build
        path: build/
